{% set name = "CausalEGM" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/CausalEGM-{{ version }}.tar.gz
  sha256: a1e296d5e81852e1a7b9d41122cebc0dffad12fd3906753cec6690f8f477736a

build:
  noarch: python
  entry_points:
    - "causalEGM = CausalEGM.cli:main"
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - tensorflow
    - scikit-learn
    - protobuf ==3.20.0
    - pandas
    - python-dateutil

test:
  imports:
    - CausalEGM
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SUwonglab/CausalEGM
  summary: 'CausalEGM: a general causal inference framework by encoding generative modeling'
  license: MIT
  license_file: LICENSE
  doc_url: https://causalegm.readthedocs.io/
  dev_url: https://github.com/SUwonglab/CausalEGM

extra:
  recipe-maintainers:
    - SUwonglab
